"""user_projects analiz durumu (faz 4)

Revision ID: ea14c9b32388
Revises: 28e2f1cf2e61
Create Date: 2026-07-08 17:28:03.221355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea14c9b32388'
down_revision: Union[str, None] = '28e2f1cf2e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('last_status', sa.String(length=20), nullable=True))
    op.add_column('user_projects', sa.Column('last_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'last_detail')
    op.drop_column('user_projects', 'last_status')
    # ### end Alembic commands ###
